db.pet.insertMany([
  {
    _id: 1,
    Especie: "cachorro",
    Raca: "SRD",
    Nome: "fred",
    Sexo: "M",
    DataNascimento: new Date("2010-02-21"),
    Vacinas: [
      { nome: "Antirrábica", dataAplicacao: new Date("2010-06-20") },
      { nome: "Antirrábica", dataAplicacao: new Date("2015-08-22") },
      { nome: "Antirrábica", dataAplicacao: new Date("2017-05-12") },
    ],
    client: 1,
  },
  {
    _id: 2,
    Especie: "cachorro",
    Raca: "SRD",
    Nome: "matraca",
    Sexo: "M",
    DataNascimento: new Date("2020-01-31"),
    Vacinas: [
      { nome: "V8", dataAplicacao: new Date("2020-02-21") },
      { nome: "V8", dataAplicacao: new Date("2020-03-17") },
      { nome: "V8", dataAplicacao: new Date("2020-04-20") },
      { nome: "Antirrábica", dataAplicacao: new Date("2020-04-20") },
    ],
    client: 2,
  },
  {
    _id: 3,
    Especie: "cachorro",
    Raca: "husky",
    Nome: "hulk",
    Sexo: "M",
    Vacinas: [
      { nome: "Antirrábica", dataAplicacao: new Date("2019-04-20") },
      { nome: "Antirrábica", dataAplicacao: new Date("2020-04-10") },
      { nome: "Antirrábica", dataAplicacao: new Date("2021-04-15") },
    ],
    client: 3,
  },
  {
    _id: 4,
    Especie: "cachorro",
    Raca: "pitbull",
    Nome: "thor",
    Sexo: "M",
    DataNascimento: new Date("2013-03-13"),
    Vacinas: [
      { nome: "Antirrábica", dataAplicacao: new Date("2014-04-12") },
      { nome: "Antirrábica", dataAplicacao: new Date("2015-04-20") },
      { nome: "Antirrábica", dataAplicacao: new Date("2016-04-13") },
      { nome: "Antirrábica", dataAplicacao: new Date("2017-04-14") },
      { nome: "Antirrábica", dataAplicacao: new Date("2018-05-15") },
      { nome: "Antirrábica", dataAplicacao: new Date("2019-04-17") },
      { nome: "Antirrábica", dataAplicacao: new Date("2020-05-18") },
      { nome: "Antirrábica", dataAplicacao: new Date("2021-04-15") },
    ],
    client: 4,
  },
  {
    _id: 5,
    Especie: "cachorro",
    Raca: "salsisha",
    Nome: "luna",
    Sexo: "F",
    DataNascimento: new Date("2014-06-16"),
    Vacinas: [
      { nome: "Antirrábica", dataAplicacao: new Date("2014-10-12") },
      { nome: "Antirrábica", dataAplicacao: new Date("2015-10-20") },
      { nome: "Antirrábica", dataAplicacao: new Date("2016-10-13") },
      { nome: "Antirrábica", dataAplicacao: new Date("2017-10-14") },
      { nome: "Antirrábica", dataAplicacao: new Date("2018-10-15") },
      { nome: "Antirrábica", dataAplicacao: new Date("2019-10-17") },
    ],
    client: 5,
  },
  {
    _id: 6,
    Especie: "cachorro",
    Raca: "doberman",
    Nome: "tobi",
    Sexo: "M",
    DataNascimento: new Date("2018-09-15"),
    Vacinas: [],
    client: 3,
  },
  {
    _id: 7,
    Especie: "gato",
    Raca: "siames",
    Nome: "juju",
    Sexo: "F",
    Vacinas: [],
    client: 2,
  },
  {
    _id: 8,
    Especie: "gato",
    Raca: "SRD",
    Nome: "valentina",
    Sexo: "F",
    DataNascimento: new Date("2010-01-11"),
    Vacinas: [],
    client: 2,
  },
  {
    _id: 9,
    Especie: "roedor",
    Raca: "hamster",
    Nome: "Larry",
    Sexo: "M",
    DataNascimento: new Date("2019-10-12"),
    Vacinas: [],
    client: 6,
  },
]);
